In [33]:
import pandas as pd
import numpy as np
import seaborn as sn

In [34]:
dataset = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv", sep=",")
dataset.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [35]:
dataset.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [ ]:
dataset.loc[dataset['SeniorCitizen'] == 1, "SeniorCitizen"] = 'Yes'
dataset.loc[dataset['SeniorCitizen'] == 0, "SeniorCitizen"] = 'No'

C:\Users\lepab\AppData\Local\Temp\ipykernel_15400\3278227426.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Yes' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  dataset.loc[dataset['SeniorCitizen'] == 1, "SeniorCitizen"] = 'Yes'

In [51]:
pd.crosstab(
    dataset["gender"],
    dataset['Churn'],
    normalize="index"
)

Churn         No       Yes
gender
Female  0.730791  0.269209
Male    0.738397  0.261603