In [2]:
import pandas as pd
import statistics as sts
import numpy as np

In [3]:
dataset = pd.read_csv("Dataset/E-Commerce Sales Analytics.csv", sep=",")

dataset.head(10)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
5,10006,1/6/2022,1071,Electronics,West,2,264.44,0.20,Card,3,3.3,423.10
6,10007,1/7/2022,1700,Clothing,South,6,564.60,0.23,Card,1,1.8,2608.45
7,10008,1/8/2022,1020,Beauty,North,6,265.71,0.13,Card,2,3.7,1387.01
8,10009,1/9/2022,1614,Clothing,South,6,224.65,0.27,Card,2,1.4,983.97
9,10010,1/10/2022,1121,Clothing,West,4,272.71,0.06,Card,10,4.5,1025.39

In [4]:
dataset.nlargest(10, "revenue")

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
809,10810,3/20/2024,1890,Electronics,South,7,594.42,0.01,Card,4,4.9,4119.33
4883,14884,5/16/2035,1146,Electronics,South,7,583.31,0.00,Card,5,4.4,4083.17
2214,12215,1/24/2028,1113,Electronics,South,7,591.15,0.02,Wallet,1,3.2,4055.29
3101,13102,6/29/2030,1699,Beauty,East,7,596.12,0.04,COD,6,3.0,4005.93
3686,13687,2/4/2032,1831,Clothing,North,7,578.59,0.03,COD,8,1.6,3928.63
157,10158,6/7/2022,1779,Electronics,North,7,571.07,0.02,COD,10,4.5,3917.54
3349,13350,3/4/2031,1082,Electronics,West,7,574.15,0.03,Card,10,2.7,3898.48
321,10322,11/18/2022,1608,Electronics,West,7,585.43,0.05,Card,10,3.2,3893.11
661,10662,10/24/2023,1550,Clothing,East,7,581.67,0.05,COD,3,1.2,3868.11
4305,14306,10/15/2033,1283,Beauty,South,7,555.09,0.02,COD,11,4.9,3807.92

In [5]:
dataset[dataset.duplicated(['order_id'], keep= False)]

Empty DataFrame
Columns: [order_id, order_date, customer_id, product_category, region, quantity, unit_price, discount, payment_method, delivery_days, customer_rating, revenue]
Index: []